### ISSUE TITLE
How to use the wildcard match ("*")?

### ISSUE THREAD

**Issue by tjapa** [tclh123/icinga2-api#1]
I'm trying something like:

`api.objects.hosts.get(filter='host.name == "*pattern-name*"')`

but doesn't work. How do I do something like that?

**Comment by tclh123** [comment]
Hi,

You could try this
```
api.objects.hosts.get(filter='match("*pattern-name*", host.name)')
```

[This](https://github.com/douban/sa-tools-core/blob/master/sa_tools_core/icinga.py#L171) is worth to check.

**Comment by tjapa** [comment]
Thank you! I'll check.
